name: "Ruida Bridge"
version: "0.9.1"
slug: "ruida_bridge"
description: "Home Assistant app for bridging Ruida controller functions into Home Assistant."
init: false
arch:
  - amd64
  - aarch64
startup: application
boot: auto
host_network: true

ingress: true
ingress_port: 8099
panel_icon: mdi:bridge
panel_title: Ruida Bridge

map:
  - type: addon_config
    read_only: false
  - type: homeassistant_config
    read_only: false

options:
  mqtt_host: "core-mosquitto"
  mqtt_user: ""
  mqtt_pass: ""
  ruida_ip: "0.0.0.0"
  override_controller_extents: false

schema:
  override_controller_extents: bool
  mqtt_host: str
  mqtt_user: str?
  mqtt_pass: password?
  ruida_ip: str
  ruida_max_x_mm: float?
  ruida_max_y_mm: float?
  ruida_max_z_mm: float?

  mqtt_port: port?
  mqtt_topic_prefix: str?
  mqtt_client_id: str?
  ha_discovery_prefix: str?
  ruida_port: port?
  ruida_local_port: port?
  ruida_z_button_step_mm: int(1,100)?
  device_id: str?
  device_name: str?
  entity_prefix: str?
